# Generated by Django 3.2 on 2021-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=200.0),
            preserve_default=False,
        ),
    ]
